
services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    container_name: car_api
    ports:
      - "8000:8000"
    volumes:
      - ../models:/app/models
    networks:
      - car_net
    restart: unless-stopped

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    container_name: car_ui
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:8000/predict
    depends_on:
      - backend
    networks:
      - car_net
    restart: unless-stopped

networks:
  car_net:
    driver: bridge
